const {
  VUE_APP_NAME: NAME,
  VUE_APP_SPECIALIZATION: SPECIALIZATION,
  VUE_APP_PIN: PIN,
  VUE_APP_STATUS: STATUS,
  VUE_APP_UNFOUND: UNFOUND,
} = process.env

export default {
  NAME,
  SPECIALIZATION,
  PIN,
  STATUS,
  UNFOUND,
}
