const {
  VUE_APP_NAME: NAME,
  VUE_APP_DESCRIPTION: DESCRIPTION,
  VUE_APP_SPECIALIZATION: SPECIALIZATION,
  VUE_APP_STATUS: STATUS,
} = process.env

export default {
  NAME,
  DESCRIPTION,
  SPECIALIZATION,
  STATUS,
}
